version: '3'
services:
    postgres:
        container_name: inmanta_db
        image: postgres:13
        environment:
            POSTGRES_USER: inmanta
            POSTGRES_PASSWORD: inmanta
        networks:
            inm_net:
                ipv4_address: 172.30.0.2

    inmanta-server:
        container_name: inmanta_orchestrator
        image: ghcr.io/edvgui/inmanta-vscode:latest
        build: ./build
        volumes:
            - ./build/resources/code-server-config.yml:/var/lib/inmanta/.config/code-server/config.yaml
            - ./build/resources/code-server-settings.json:/var/lib/inmanta/.local/share/code-server/User/settings.json
        networks:
            inm_net:
                ipv4_address: 172.30.0.3
        command: "server --wait-for-host inmanta_db --wait-for-port 5432"

networks:
    inm_net:
        ipam:
            driver: default
            config:
                - subnet: 172.30.0.0/16
